author: Minor Gordon
branding:
  icon: loader
description: Generate a static site from a Paradicms-formatted spreadsheet.
inputs:
  build_directory_path:
    default: _site
    description: Path to a directory where the generated static assets (CSS, HTML,
      JavaScript) should be placed
    required: false
  data_file_paths:
    description: Colon-separated paths to one or more data files
    required: false
  debug:
    description: Debug the action
    required: false
  pipeline_id:
    description: Pipeline id. Defaults to the name of the repository.
    required: false
  spreadsheet:
    description: Google Sheets spreadsheet id, Google Sheet URL, or path to an Excel
      2010 (.xlsx) file
    required: true
name: Generate a static site from a Paradicms-formatted spreadsheet.
runs:
  image: Dockerfile
  using: docker
