name: "Generate a static site using Paradicms"
description: "Generate a static site using Paradicms"
author: "Minor Gordon"
branding:
  icon: "loader"
inputs:
  app:
    description: Directory name of a well-known paradicms app (e.g., work-search) or path to the root directory of another app
    required: true
  app_configuration:
    description: Path to a configuration file, which controls the static site generator
    required: false
  debug:
    description: Debug the action
    required: false
  pipeline_id:
    description: Pipeline id. Defaults to the name of the repository.
    required: false
  spreadsheet_id:
    description: Google Sheets spreadsheet id, must be publicly accessible to anyone with the link
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
