author: Minor Gordon
branding:
  icon: loader
description: Extract, transform, and load data from a Paradicms-formatted spreadsheet.
inputs:
  cache_directory_path:
    default: .paradicms/.cache
    description: Path to a directory in which to store cached data
    required: false
  debug:
    description: Debug the action
    required: false
  loaded_data_directory_path:
    default: .paradicms/data
    description: Path to a directory in which to store the loaded RDF file
    required: false
  loaded_data_file_path:
    description: Path to a file in which to store the loaded RDF, overrides data_directory_path
      if specified
    required: false
  pipeline_id:
    description: Pipeline id. Defaults to the name of the repository.
    required: false
  spreadsheet:
    description: Google Sheets spreadsheet id, Google Sheet URL, or path to an Excel
      2010 (.xlsx) file
    required: true
name: Extract, transform, and load data from a Paradicms-formatted spreadsheet.
runs:
  image: Dockerfile
  using: docker
