name: "paradicms gui"
description: "Extract, transform, and load data into paradicms-compatible RDF and generate a static site from it"
author: "Minor Gordon"
branding:
  icon: "loader"
inputs:
  base_url_path:
    description: Next.js basePath (https://nextjs.org/docs/api-reference/next.config.js/basepath)
    required: false
  configuration_json_file_path:
    description: Path to a configuration.json file, which controls the static site generator.
    required: false
  debug:
    description: Debug the action
    required: false
  id:
    description: Pipeline id. Defaults to the name of the repository.
    required: false
  input_data:
    description: Path to your input data. It can be a directory or a file, depending on the input format.
    required: true
  input_format:
    description: The format of the input data.
    required: true
  output_data:
    description: Path to your output data. It can be a directory or a file, depending on the output format.
    required: true
  output_format:
    description: The desired format of the output data.
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
