author: Minor Gordon
branding:
  icon: loader
description: Extract, transform, and load data from a Paradicms-formatted spreadsheet.
inputs:
  data_directory_path:
    default: _data
    description: Path to a directory where extracted/ and loaded/ data should be stored
    required: false
  debug:
    description: Debug the action
    required: false
  pipeline_id:
    description: Pipeline id. Defaults to the name of the repository.
    required: false
  spreadsheet:
    description: Google Sheets spreadsheet id, Google Sheet URL, or path to an Excel
      2010 (.xlsx) file
    required: true
name: Extract, transform, and load data from a Paradicms-formatted spreadsheet.
runs:
  image: Dockerfile
  using: docker
